version: '3'

services:
  whisper_server:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: whisper:20230314
    container_name: whisper_server
    volumes:
      - ../src_server:/app/src
    working_dir: /app
    ports:
      - "7870:5000"
    tty: true
    entrypoint: sh -c "cd /app/src && uvicorn main:app --host 0.0.0.0 --reload --port 5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  whisper_client:
    image: python:3.10
    container_name: whisper_client
    volumes:
      - ../src_client:/app/src
      - ../voice_recordings:/app/voice_recordings
    working_dir: /app
    tty: true
