version: '3'

services:
  openai_whisper_server:
    build:
      context: ../Dockerfile_openai_whisper
      dockerfile: Dockerfile
    image: openai_whisper:20231117
    container_name: openai_whisper_server
    volumes:
      - ../src_openai_whisper_server:/app/src
      - ../logging.conf:/app/logging.conf
    working_dir: /app
    ports:
      - "7870:5000"
    tty: true
    entrypoint: sh -c "cd /app/src && uvicorn main:app --host 0.0.0.0 --reload --port 5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  faster_whisper_server:
    build:
      context: ../Dockerfile_faster_whisper
      dockerfile: Dockerfile
    image: faster_whisper:0.10.0
    container_name: faster_whisper_server
    volumes:
      - ../src_faster_whisper_server:/app/src
      - ../logging.conf:/app/logging.conf
    working_dir: /app
    ports:
      - "7871:5000"
    tty: true
    entrypoint: sh -c "cd /app/src && uvicorn main:app --host 0.0.0.0 --reload --port 5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  whisper_client:
    image: python:3.10
    container_name: whisper_client
    volumes:
      - ../src_client:/app/src
      - ../pytest.ini:/app/pytest.ini
    working_dir: /app
    tty: true
