version: '3'

services:
  openai_whisper_server:
    build:
      context: ../Dockerfile/openai_whisper
      dockerfile: Dockerfile
    image: openai_whisper:20231117
    container_name: openai_whisper_server
    volumes:
      - ../src/openai_whisper_server:/app/src
      - ../logging.conf:/app/logging.conf
    working_dir: /app
    ports:
      - "7860:7860"
    environment:
      PYTHONPATH: /app/src/
    tty: true
    entrypoint: sh -c "cd /app/src && python3 gradio_app.py --server_name 0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  faster_whisper_server:
    build:
      context: ../Dockerfile/faster_whisper
      dockerfile: Dockerfile
    image: faster_whisper:0.10.0
    container_name: faster_whisper_server
    volumes:
      - ../src/faster_whisper_server:/app/src
      - ../logging.conf:/app/logging.conf
    working_dir: /app
    ports:
      - "7861:7860"
    environment:
      PYTHONPATH: /app/src/
    tty: true
    entrypoint: sh -c "cd /app/src/ && python3 gradio_app.py --server_name 0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  kotoba_whisper_server:
    build:
      context: ../Dockerfile/kotoba_whisper
      dockerfile: Dockerfile
    image: kotoba_whisper
    container_name: kotoba_whisper_server
    volumes:
      - ../src/kotoba_whisper_server:/app/src
      - ../logging.conf:/app/logging.conf
    working_dir: /app
    ports:
      - "7862:7860"
    environment:
      PYTHONPATH: /app/src/
    tty: true
    entrypoint: sh -c "cd /app/src && python3 gradio_app.py --server_name 0.0.0.0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  whisper_test_client:
    image: python:3.10
    container_name: whisper_test_client
    volumes:
      - ../test:/app/test
      - ../pytest.ini:/app/pytest.ini
    working_dir: /app
    tty: true
